# Generated by Django 4.2.3 on 2023-07-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calories_burnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('Joule', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='distance_covered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('KM', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='heart_rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('BPM', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='step_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('Count', models.FloatField()),
            ],
        ),
    ]
